### ISSUE TITLE
Choco is too handsome

### ISSUE THREAD

**Issue by lamlaaaam** [ChocoMeow/IUFI#1]
see title

**Comment by ChocoMeow** [comment]
let's see how to solve this problem

**Comment by Arieswaran** [comment]
I am also having the same issue. Sharing the traceback logs

```
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    bot.run(token)
  File "cutebot.py", line 123, in run
    await self.handle_cuteness_error()
  File "cutebot.py", line 89, in handle_cuteness_error
    raise ChocoTooCuteException("Cuteness overload detected!")
cutebot.ChocoTooCuteException: Cuteness overload detected!
```
